import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers, ProvidersNextUI } from "./Providers";
import Navbar from "@/components/Navbar";

const inter = Montserrat({ subsets: ["latin"], weight: "700" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ProvidersNextUI>
          <Providers>
            <Navbar />
            <div className="container mx-auto">{children}</div>
          </Providers>
        </ProvidersNextUI>
      </body>
    </html>
  );
}
